plugins {
    id 'com.android.application' version '8.7.3'
}

android {
    namespace 'com.physiqueterminale.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.physiqueterminale.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
}
